name: Weekly Bot Runner

on:
  schedule:
    - cron: '0 0 * * 0'  # Her Pazar gece yarısı
  workflow_dispatch:      # Manuel çalıştırma butonu için

jobs:
  ihtiyac-kredisi:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - run: |
          mkdir -p Data
          pip install selenium webdriver_manager firebase-admin
          cd Bots
          python -u ihtiyac_kredisi_bot.py || true
          echo "Bot çalışması tamamlandı"
          ls -la ../Data/
          exit 0

  tasit-kredisi:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - run: |
          mkdir -p Data
          pip install selenium webdriver_manager firebase-admin
          cd Bots
          python -u tasit_kredisi_bot.py || true
          echo "Bot çalışması tamamlandı"
          ls -la ../Data/
          exit 0

  konut-kredisi:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - run: |
          mkdir -p Data
          pip install selenium webdriver_manager firebase-admin
          cd Bots
          python -u konut_kredisi_bot.py || true
          echo "Bot çalışması tamamlandı"
          ls -la ../Data/
          exit 0

  kobi-kredisi:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - run: |
          mkdir -p Data
          pip install selenium webdriver_manager firebase-admin
          cd Bots
          python -u kobi_bot.py || true
          echo "Bot çalışması tamamlandı"
          ls -la ../Data/
          exit 0

  mevduat:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - run: |
          mkdir -p Data
          pip install selenium webdriver_manager firebase-admin
          cd Bots
          python -u mevduat_bot.py || true
          echo "Bot çalışması tamamlandı"
          ls -la ../Data/
          exit 0

  finalize:
    if: always()  # Diğer joblar başarısız olsa bile çalışır
    needs: [ihtiyac-kredisi, tasit-kredisi, konut-kredisi, kobi-kredisi, mevduat]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: Data
      - name: Setup Firebase credentials
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > serviceAccountKey.json
          echo "${{ secrets.MEVDUAT_SERVICE_ACCOUNT }}" > mevduatServiceAccountKey.json
          echo "${{ secrets.MEVDUAT2_SERVICE_ACCOUNT }}" > mevduat2serviceAccountKey.json
      - name: Process and Upload
        if: always()
        run: |
          python split_mevduat.py || true
          python db_setup.py || true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: scraped-data
          path: Data/
          retention-days: 7
      - name: Cleanup
        if: always()
        run: |
          rm -f serviceAccountKey.json
          rm -f mevduatServiceAccountKey.json
          rm -f mevduat2serviceAccountKey.json 
