name: Bot Automation

on:
  schedule:
    - cron: '0 0 * * 0'  # Her Pazar günü saat 00:00'da
  workflow_dispatch:  # Manuel tetikleme
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-bots:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Data directory
      run: |
        if [ ! -d "Data" ]; then
          mkdir Data
        fi
        echo "Data directory contents:"
        ls -la Data/

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager firebase-admin

    - name: Setup Firebase credentials
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > serviceAccountKey.json
        echo "${{ secrets.MEVDUAT_SERVICE_ACCOUNT }}" > mevduatServiceAccountKey.json
        echo "${{ secrets.MEVDUAT2_SERVICE_ACCOUNT }}" > mevduat2serviceAccountKey.json

    - name: Run bots
      continue-on-error: true
      run: |
        cd Bots
        for bot in ihtiyac_kredisi_bot.py kobi_bot.py konut_kredisi_bot.py mevduat_bot.py; do
          echo "Running $bot..."
          timeout 20m python -u $bot || echo "Warning: $bot timed out or failed"
          echo "Completed running $bot"
          echo "Current Data directory contents:"
          ls -la ../Data/
          echo "----------------------------------------"
        done
        cd ..

    - name: Process data
      if: always()
      continue-on-error: true
      run: |
        echo "Running split_mevduat.py..."
        python split_mevduat.py || echo "Warning: split_mevduat.py failed"
        echo "Running db_setup.py..."
        python db_setup.py || echo "Warning: db_setup.py failed"
        echo "Data processing completed"
        echo "Final Data directory contents:"
        ls -la Data/

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bot-data-${{ github.run_number }}
        path: Data/
        retention-days: 7

    - name: Cleanup sensitive files
      if: always()
      run: |
        rm -f serviceAccountKey.json
        rm -f mevduatServiceAccountKey.json
        rm -f mevduat2serviceAccountKey.json
