name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Create Data directory
      run: mkdir -p Data

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager firebase-admin

    - name: Setup Firebase credentials
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > serviceAccountKey.json
        echo "${{ secrets.MEVDUAT_SERVICE_ACCOUNT }}" > mevduatServiceAccountKey.json
        echo "${{ secrets.MEVDUAT2_SERVICE_ACCOUNT }}" > mevduat2serviceAccountKey.json

    - name: Run bots
      run: |
        cd Bots
        for bot in ihtiyac_kredisi_bot.py kobi_bot.py konut_kredisi_bot.py mevduat_bot.py; do
          python -u $bot || true
          echo "Completed running $bot"
          ls -la ../Data/
        done
        cd ..

    - name: Process data
      if: always()
      run: |
        python split_mevduat.py || true
        python db_setup.py || true

    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: scraped-data
        path: Data/
        retention-days: 7

    - name: Cleanup
      if: always()
      run: |
        rm -f serviceAccountKey.json
        rm -f mevduatServiceAccountKey.json
        rm -f mevduat2serviceAccountKey.json
