name: Bot Automation

on:
  schedule:
    - cron: '0 0 * * 0'  # Her Pazar günü saat 00:00'da
  workflow_dispatch:  # Manuel tetikleme
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-bots:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Data directory
      run: |
        mkdir -p Data
        chmod 777 Data
        echo "Working directory structure:"
        tree .

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager firebase-admin

    - name: Setup Firebase credentials
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > serviceAccountKey.json
        echo "${{ secrets.MEVDUAT_SERVICE_ACCOUNT }}" > mevduatServiceAccountKey.json
        echo "${{ secrets.MEVDUAT2_SERVICE_ACCOUNT }}" > mevduat2serviceAccountKey.json

    - name: Run bots
      continue-on-error: true
      run: |
        # Absolute paths for debugging
        echo "Absolute path to Data directory: $PWD/Data"
        echo "Absolute path to Bots directory: $PWD/Bots"
        
        cd Bots
        for bot in ihtiyac_kredisi_bot.py kobi_bot.py konut_kredisi_bot.py mevduat_bot.py; do
          echo "----------------------------------------"
          echo "Running $bot..."
          python -u $bot
          if [ $? -eq 0 ]; then
            echo "Successfully completed $bot"
          else
            echo "Warning: $bot failed with exit code $?"
          fi
          echo "Data directory contents:"
          ls -la ../Data/
        done
        cd ..

    - name: Process data
      if: always()
      continue-on-error: true
      run: |
        echo "Data directory contents before processing:"
        ls -la Data/
        
        if [ -f "Data/mevduat.json" ]; then
          echo "Running split_mevduat.py..."
          python split_mevduat.py
        else
          echo "Warning: mevduat.json not found, skipping split"
        fi
        
        echo "Running db_setup.py..."
        python db_setup.py
        
        echo "Final Data directory contents:"
        ls -la Data/

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bot-data-${{ github.run_number }}
        path: Data/
        if-no-files-found: warn

    - name: Cleanup sensitive files
      if: always()
      run: |
        rm -f serviceAccountKey.json
        rm -f mevduatServiceAccountKey.json
        rm -f mevduat2serviceAccountKey.json
