name: Bot Automation

on:
  schedule:
    - cron: '0 0 * * 0'  # Her Pazar günü saat 00:00'da
  workflow_dispatch:  # Manuel tetikleme
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-bots:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Timeout süresini artıralım

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Data directory
      run: |
        mkdir -p Data
        chmod 777 Data
        echo "Working directory structure:"
        tree .

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager firebase-admin

    - name: Setup Firebase credentials
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > serviceAccountKey.json
        echo "${{ secrets.MEVDUAT_SERVICE_ACCOUNT }}" > mevduatServiceAccountKey.json
        echo "${{ secrets.MEVDUAT2_SERVICE_ACCOUNT }}" > mevduat2serviceAccountKey.json

    - name: Run ihtiyac kredisi bot
      continue-on-error: true
      timeout-minutes: 15
      run: |
        cd Bots
        echo "Running ihtiyac_kredisi_bot.py..."
        python -u ihtiyac_kredisi_bot.py || echo "Warning: Bot failed"
        cd ..

    - name: Run konut kredisi bot
      continue-on-error: true
      timeout-minutes: 15
      run: |
        cd Bots
        echo "Running konut_kredisi_bot.py..."
        python -u konut_kredisi_bot.py || echo "Warning: Bot failed"
        cd ..

    - name: Run kobi kredisi bot
      continue-on-error: true
      timeout-minutes: 15
      run: |
        cd Bots
        echo "Running kobi_bot.py..."
        python -u kobi_bot.py || echo "Warning: Bot failed"
        cd ..

    - name: Run mevduat bot
      continue-on-error: true
      timeout-minutes: 15
      run: |
        cd Bots
        echo "Running mevduat_bot.py..."
        python -u mevduat_bot.py || echo "Warning: Bot failed"
        cd ..

    - name: Process data
      if: always()
      continue-on-error: true
      run: |
        echo "Data directory contents before processing:"
        ls -la Data/
        
        if [ -f "Data/mevduat.json" ]; then
          echo "Running split_mevduat.py..."
          python split_mevduat.py
        else
          echo "Warning: mevduat.json not found, skipping split"
        fi
        
        if [ -f "Data/ihtiyac_kredisi_data.json" ] || [ -f "Data/konut_kredisi_data.json" ] || [ -f "Data/kobi_kredisi_data.json" ]; then
          echo "Running db_setup.py..."
          python db_setup.py
        else
          echo "Warning: No credit data files found, skipping db_setup"
        fi
        
        echo "Final Data directory contents:"
        ls -la Data/

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bot-data-${{ github.run_number }}
        path: Data/
        if-no-files-found: warn

    - name: Cleanup sensitive files
      if: always()
      run: |
        rm -f serviceAccountKey.json
        rm -f mevduatServiceAccountKey.json
        rm -f mevduat2serviceAccountKey.json
